// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SeyramWood/bookibus/ent/company"
	"github.com/SeyramWood/bookibus/ent/predicate"
	"github.com/SeyramWood/bookibus/ent/terminal"
	"github.com/SeyramWood/bookibus/ent/trip"
)

// TerminalQuery is the builder for querying Terminal entities.
type TerminalQuery struct {
	config
	ctx         *QueryContext
	order       []terminal.OrderOption
	inters      []Interceptor
	predicates  []predicate.Terminal
	withCompany *CompanyQuery
	withFrom    *TripQuery
	withTo      *TripQuery
	withFKs     bool
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TerminalQuery builder.
func (tq *TerminalQuery) Where(ps ...predicate.Terminal) *TerminalQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TerminalQuery) Limit(limit int) *TerminalQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TerminalQuery) Offset(offset int) *TerminalQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TerminalQuery) Unique(unique bool) *TerminalQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TerminalQuery) Order(o ...terminal.OrderOption) *TerminalQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryCompany chains the current query on the "company" edge.
func (tq *TerminalQuery) QueryCompany() *CompanyQuery {
	query := (&CompanyClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(terminal.Table, terminal.FieldID, selector),
			sqlgraph.To(company.Table, company.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, terminal.CompanyTable, terminal.CompanyColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFrom chains the current query on the "from" edge.
func (tq *TerminalQuery) QueryFrom() *TripQuery {
	query := (&TripClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(terminal.Table, terminal.FieldID, selector),
			sqlgraph.To(trip.Table, trip.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, terminal.FromTable, terminal.FromColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTo chains the current query on the "to" edge.
func (tq *TerminalQuery) QueryTo() *TripQuery {
	query := (&TripClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(terminal.Table, terminal.FieldID, selector),
			sqlgraph.To(trip.Table, trip.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, terminal.ToTable, terminal.ToColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Terminal entity from the query.
// Returns a *NotFoundError when no Terminal was found.
func (tq *TerminalQuery) First(ctx context.Context) (*Terminal, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{terminal.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TerminalQuery) FirstX(ctx context.Context) *Terminal {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Terminal ID from the query.
// Returns a *NotFoundError when no Terminal ID was found.
func (tq *TerminalQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{terminal.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TerminalQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Terminal entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Terminal entity is found.
// Returns a *NotFoundError when no Terminal entities are found.
func (tq *TerminalQuery) Only(ctx context.Context) (*Terminal, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{terminal.Label}
	default:
		return nil, &NotSingularError{terminal.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TerminalQuery) OnlyX(ctx context.Context) *Terminal {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Terminal ID in the query.
// Returns a *NotSingularError when more than one Terminal ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TerminalQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{terminal.Label}
	default:
		err = &NotSingularError{terminal.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TerminalQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Terminals.
func (tq *TerminalQuery) All(ctx context.Context) ([]*Terminal, error) {
	ctx = setContextOp(ctx, tq.ctx, "All")
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Terminal, *TerminalQuery]()
	return withInterceptors[[]*Terminal](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TerminalQuery) AllX(ctx context.Context) []*Terminal {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Terminal IDs.
func (tq *TerminalQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, "IDs")
	if err = tq.Select(terminal.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TerminalQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TerminalQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, "Count")
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TerminalQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TerminalQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TerminalQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, "Exist")
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TerminalQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TerminalQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TerminalQuery) Clone() *TerminalQuery {
	if tq == nil {
		return nil
	}
	return &TerminalQuery{
		config:      tq.config,
		ctx:         tq.ctx.Clone(),
		order:       append([]terminal.OrderOption{}, tq.order...),
		inters:      append([]Interceptor{}, tq.inters...),
		predicates:  append([]predicate.Terminal{}, tq.predicates...),
		withCompany: tq.withCompany.Clone(),
		withFrom:    tq.withFrom.Clone(),
		withTo:      tq.withTo.Clone(),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// WithCompany tells the query-builder to eager-load the nodes that are connected to
// the "company" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TerminalQuery) WithCompany(opts ...func(*CompanyQuery)) *TerminalQuery {
	query := (&CompanyClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withCompany = query
	return tq
}

// WithFrom tells the query-builder to eager-load the nodes that are connected to
// the "from" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TerminalQuery) WithFrom(opts ...func(*TripQuery)) *TerminalQuery {
	query := (&TripClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withFrom = query
	return tq
}

// WithTo tells the query-builder to eager-load the nodes that are connected to
// the "to" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TerminalQuery) WithTo(opts ...func(*TripQuery)) *TerminalQuery {
	query := (&TripClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withTo = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Terminal.Query().
//		GroupBy(terminal.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TerminalQuery) GroupBy(field string, fields ...string) *TerminalGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TerminalGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = terminal.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Terminal.Query().
//		Select(terminal.FieldCreatedAt).
//		Scan(ctx, &v)
func (tq *TerminalQuery) Select(fields ...string) *TerminalSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TerminalSelect{TerminalQuery: tq}
	sbuild.label = terminal.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TerminalSelect configured with the given aggregations.
func (tq *TerminalQuery) Aggregate(fns ...AggregateFunc) *TerminalSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TerminalQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !terminal.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TerminalQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Terminal, error) {
	var (
		nodes       = []*Terminal{}
		withFKs     = tq.withFKs
		_spec       = tq.querySpec()
		loadedTypes = [3]bool{
			tq.withCompany != nil,
			tq.withFrom != nil,
			tq.withTo != nil,
		}
	)
	if tq.withCompany != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, terminal.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Terminal).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Terminal{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tq.modifiers) > 0 {
		_spec.Modifiers = tq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withCompany; query != nil {
		if err := tq.loadCompany(ctx, query, nodes, nil,
			func(n *Terminal, e *Company) { n.Edges.Company = e }); err != nil {
			return nil, err
		}
	}
	if query := tq.withFrom; query != nil {
		if err := tq.loadFrom(ctx, query, nodes,
			func(n *Terminal) { n.Edges.From = []*Trip{} },
			func(n *Terminal, e *Trip) { n.Edges.From = append(n.Edges.From, e) }); err != nil {
			return nil, err
		}
	}
	if query := tq.withTo; query != nil {
		if err := tq.loadTo(ctx, query, nodes,
			func(n *Terminal) { n.Edges.To = []*Trip{} },
			func(n *Terminal, e *Trip) { n.Edges.To = append(n.Edges.To, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TerminalQuery) loadCompany(ctx context.Context, query *CompanyQuery, nodes []*Terminal, init func(*Terminal), assign func(*Terminal, *Company)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Terminal)
	for i := range nodes {
		if nodes[i].company_terminals == nil {
			continue
		}
		fk := *nodes[i].company_terminals
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(company.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "company_terminals" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tq *TerminalQuery) loadFrom(ctx context.Context, query *TripQuery, nodes []*Terminal, init func(*Terminal), assign func(*Terminal, *Trip)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Terminal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Trip(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(terminal.FromColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.terminal_from
		if fk == nil {
			return fmt.Errorf(`foreign-key "terminal_from" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "terminal_from" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (tq *TerminalQuery) loadTo(ctx context.Context, query *TripQuery, nodes []*Terminal, init func(*Terminal), assign func(*Terminal, *Trip)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Terminal)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Trip(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(terminal.ToColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.terminal_to
		if fk == nil {
			return fmt.Errorf(`foreign-key "terminal_to" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "terminal_to" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tq *TerminalQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	if len(tq.modifiers) > 0 {
		_spec.Modifiers = tq.modifiers
	}
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TerminalQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(terminal.Table, terminal.Columns, sqlgraph.NewFieldSpec(terminal.FieldID, field.TypeInt))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, terminal.FieldID)
		for i := range fields {
			if fields[i] != terminal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TerminalQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(terminal.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = terminal.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tq.modifiers {
		m(selector)
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tq *TerminalQuery) Modify(modifiers ...func(s *sql.Selector)) *TerminalSelect {
	tq.modifiers = append(tq.modifiers, modifiers...)
	return tq.Select()
}

// TerminalGroupBy is the group-by builder for Terminal entities.
type TerminalGroupBy struct {
	selector
	build *TerminalQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TerminalGroupBy) Aggregate(fns ...AggregateFunc) *TerminalGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TerminalGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, "GroupBy")
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TerminalQuery, *TerminalGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TerminalGroupBy) sqlScan(ctx context.Context, root *TerminalQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TerminalSelect is the builder for selecting fields of Terminal entities.
type TerminalSelect struct {
	*TerminalQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TerminalSelect) Aggregate(fns ...AggregateFunc) *TerminalSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TerminalSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, "Select")
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TerminalQuery, *TerminalSelect](ctx, ts.TerminalQuery, ts, ts.inters, v)
}

func (ts *TerminalSelect) sqlScan(ctx context.Context, root *TerminalQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ts *TerminalSelect) Modify(modifiers ...func(s *sql.Selector)) *TerminalSelect {
	ts.modifiers = append(ts.modifiers, modifiers...)
	return ts
}
