// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SeyramWood/ent/company"
	"github.com/SeyramWood/ent/trip"
	"github.com/SeyramWood/ent/vehicle"
	"github.com/SeyramWood/ent/vehicleimage"
)

// VehicleCreate is the builder for creating a Vehicle entity.
type VehicleCreate struct {
	config
	mutation *VehicleMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (vc *VehicleCreate) SetCreatedAt(t time.Time) *VehicleCreate {
	vc.mutation.SetCreatedAt(t)
	return vc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vc *VehicleCreate) SetNillableCreatedAt(t *time.Time) *VehicleCreate {
	if t != nil {
		vc.SetCreatedAt(*t)
	}
	return vc
}

// SetUpdatedAt sets the "updated_at" field.
func (vc *VehicleCreate) SetUpdatedAt(t time.Time) *VehicleCreate {
	vc.mutation.SetUpdatedAt(t)
	return vc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (vc *VehicleCreate) SetNillableUpdatedAt(t *time.Time) *VehicleCreate {
	if t != nil {
		vc.SetUpdatedAt(*t)
	}
	return vc
}

// SetRegistrationNumber sets the "registration_number" field.
func (vc *VehicleCreate) SetRegistrationNumber(s string) *VehicleCreate {
	vc.mutation.SetRegistrationNumber(s)
	return vc
}

// SetModel sets the "model" field.
func (vc *VehicleCreate) SetModel(s string) *VehicleCreate {
	vc.mutation.SetModel(s)
	return vc
}

// SetSeat sets the "seat" field.
func (vc *VehicleCreate) SetSeat(i int) *VehicleCreate {
	vc.mutation.SetSeat(i)
	return vc
}

// SetNillableSeat sets the "seat" field if the given value is not nil.
func (vc *VehicleCreate) SetNillableSeat(i *int) *VehicleCreate {
	if i != nil {
		vc.SetSeat(*i)
	}
	return vc
}

// SetCompanyID sets the "company" edge to the Company entity by ID.
func (vc *VehicleCreate) SetCompanyID(id int) *VehicleCreate {
	vc.mutation.SetCompanyID(id)
	return vc
}

// SetNillableCompanyID sets the "company" edge to the Company entity by ID if the given value is not nil.
func (vc *VehicleCreate) SetNillableCompanyID(id *int) *VehicleCreate {
	if id != nil {
		vc = vc.SetCompanyID(*id)
	}
	return vc
}

// SetCompany sets the "company" edge to the Company entity.
func (vc *VehicleCreate) SetCompany(c *Company) *VehicleCreate {
	return vc.SetCompanyID(c.ID)
}

// AddImageIDs adds the "images" edge to the VehicleImage entity by IDs.
func (vc *VehicleCreate) AddImageIDs(ids ...int) *VehicleCreate {
	vc.mutation.AddImageIDs(ids...)
	return vc
}

// AddImages adds the "images" edges to the VehicleImage entity.
func (vc *VehicleCreate) AddImages(v ...*VehicleImage) *VehicleCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return vc.AddImageIDs(ids...)
}

// AddTripIDs adds the "trips" edge to the Trip entity by IDs.
func (vc *VehicleCreate) AddTripIDs(ids ...int) *VehicleCreate {
	vc.mutation.AddTripIDs(ids...)
	return vc
}

// AddTrips adds the "trips" edges to the Trip entity.
func (vc *VehicleCreate) AddTrips(t ...*Trip) *VehicleCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return vc.AddTripIDs(ids...)
}

// Mutation returns the VehicleMutation object of the builder.
func (vc *VehicleCreate) Mutation() *VehicleMutation {
	return vc.mutation
}

// Save creates the Vehicle in the database.
func (vc *VehicleCreate) Save(ctx context.Context) (*Vehicle, error) {
	vc.defaults()
	return withHooks(ctx, vc.sqlSave, vc.mutation, vc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (vc *VehicleCreate) SaveX(ctx context.Context) *Vehicle {
	v, err := vc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vc *VehicleCreate) Exec(ctx context.Context) error {
	_, err := vc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vc *VehicleCreate) ExecX(ctx context.Context) {
	if err := vc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vc *VehicleCreate) defaults() {
	if _, ok := vc.mutation.CreatedAt(); !ok {
		v := vehicle.DefaultCreatedAt()
		vc.mutation.SetCreatedAt(v)
	}
	if _, ok := vc.mutation.UpdatedAt(); !ok {
		v := vehicle.DefaultUpdatedAt()
		vc.mutation.SetUpdatedAt(v)
	}
	if _, ok := vc.mutation.Seat(); !ok {
		v := vehicle.DefaultSeat
		vc.mutation.SetSeat(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vc *VehicleCreate) check() error {
	if _, ok := vc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Vehicle.created_at"`)}
	}
	if _, ok := vc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Vehicle.updated_at"`)}
	}
	if _, ok := vc.mutation.RegistrationNumber(); !ok {
		return &ValidationError{Name: "registration_number", err: errors.New(`ent: missing required field "Vehicle.registration_number"`)}
	}
	if v, ok := vc.mutation.RegistrationNumber(); ok {
		if err := vehicle.RegistrationNumberValidator(v); err != nil {
			return &ValidationError{Name: "registration_number", err: fmt.Errorf(`ent: validator failed for field "Vehicle.registration_number": %w`, err)}
		}
	}
	if _, ok := vc.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "Vehicle.model"`)}
	}
	if v, ok := vc.mutation.Model(); ok {
		if err := vehicle.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Vehicle.model": %w`, err)}
		}
	}
	if _, ok := vc.mutation.Seat(); !ok {
		return &ValidationError{Name: "seat", err: errors.New(`ent: missing required field "Vehicle.seat"`)}
	}
	return nil
}

func (vc *VehicleCreate) sqlSave(ctx context.Context) (*Vehicle, error) {
	if err := vc.check(); err != nil {
		return nil, err
	}
	_node, _spec := vc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	vc.mutation.id = &_node.ID
	vc.mutation.done = true
	return _node, nil
}

func (vc *VehicleCreate) createSpec() (*Vehicle, *sqlgraph.CreateSpec) {
	var (
		_node = &Vehicle{config: vc.config}
		_spec = sqlgraph.NewCreateSpec(vehicle.Table, sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeInt))
	)
	if value, ok := vc.mutation.CreatedAt(); ok {
		_spec.SetField(vehicle.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := vc.mutation.UpdatedAt(); ok {
		_spec.SetField(vehicle.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := vc.mutation.RegistrationNumber(); ok {
		_spec.SetField(vehicle.FieldRegistrationNumber, field.TypeString, value)
		_node.RegistrationNumber = value
	}
	if value, ok := vc.mutation.Model(); ok {
		_spec.SetField(vehicle.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := vc.mutation.Seat(); ok {
		_spec.SetField(vehicle.FieldSeat, field.TypeInt, value)
		_node.Seat = value
	}
	if nodes := vc.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vehicle.CompanyTable,
			Columns: []string{vehicle.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.company_vehicles = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := vc.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vehicle.ImagesTable,
			Columns: []string{vehicle.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicleimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := vc.mutation.TripsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vehicle.TripsTable,
			Columns: []string{vehicle.TripsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VehicleCreateBulk is the builder for creating many Vehicle entities in bulk.
type VehicleCreateBulk struct {
	config
	err      error
	builders []*VehicleCreate
}

// Save creates the Vehicle entities in the database.
func (vcb *VehicleCreateBulk) Save(ctx context.Context) ([]*Vehicle, error) {
	if vcb.err != nil {
		return nil, vcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(vcb.builders))
	nodes := make([]*Vehicle, len(vcb.builders))
	mutators := make([]Mutator, len(vcb.builders))
	for i := range vcb.builders {
		func(i int, root context.Context) {
			builder := vcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VehicleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vcb *VehicleCreateBulk) SaveX(ctx context.Context) []*Vehicle {
	v, err := vcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vcb *VehicleCreateBulk) Exec(ctx context.Context) error {
	_, err := vcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vcb *VehicleCreateBulk) ExecX(ctx context.Context) {
	if err := vcb.Exec(ctx); err != nil {
		panic(err)
	}
}
