// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SeyramWood/ent/predicate"
	"github.com/SeyramWood/ent/vehicle"
	"github.com/SeyramWood/ent/vehicleimage"
)

// VehicleImageQuery is the builder for querying VehicleImage entities.
type VehicleImageQuery struct {
	config
	ctx         *QueryContext
	order       []vehicleimage.OrderOption
	inters      []Interceptor
	predicates  []predicate.VehicleImage
	withVehicle *VehicleQuery
	withFKs     bool
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VehicleImageQuery builder.
func (viq *VehicleImageQuery) Where(ps ...predicate.VehicleImage) *VehicleImageQuery {
	viq.predicates = append(viq.predicates, ps...)
	return viq
}

// Limit the number of records to be returned by this query.
func (viq *VehicleImageQuery) Limit(limit int) *VehicleImageQuery {
	viq.ctx.Limit = &limit
	return viq
}

// Offset to start from.
func (viq *VehicleImageQuery) Offset(offset int) *VehicleImageQuery {
	viq.ctx.Offset = &offset
	return viq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (viq *VehicleImageQuery) Unique(unique bool) *VehicleImageQuery {
	viq.ctx.Unique = &unique
	return viq
}

// Order specifies how the records should be ordered.
func (viq *VehicleImageQuery) Order(o ...vehicleimage.OrderOption) *VehicleImageQuery {
	viq.order = append(viq.order, o...)
	return viq
}

// QueryVehicle chains the current query on the "vehicle" edge.
func (viq *VehicleImageQuery) QueryVehicle() *VehicleQuery {
	query := (&VehicleClient{config: viq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := viq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := viq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(vehicleimage.Table, vehicleimage.FieldID, selector),
			sqlgraph.To(vehicle.Table, vehicle.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, vehicleimage.VehicleTable, vehicleimage.VehicleColumn),
		)
		fromU = sqlgraph.SetNeighbors(viq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VehicleImage entity from the query.
// Returns a *NotFoundError when no VehicleImage was found.
func (viq *VehicleImageQuery) First(ctx context.Context) (*VehicleImage, error) {
	nodes, err := viq.Limit(1).All(setContextOp(ctx, viq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{vehicleimage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (viq *VehicleImageQuery) FirstX(ctx context.Context) *VehicleImage {
	node, err := viq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VehicleImage ID from the query.
// Returns a *NotFoundError when no VehicleImage ID was found.
func (viq *VehicleImageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = viq.Limit(1).IDs(setContextOp(ctx, viq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{vehicleimage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (viq *VehicleImageQuery) FirstIDX(ctx context.Context) int {
	id, err := viq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VehicleImage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VehicleImage entity is found.
// Returns a *NotFoundError when no VehicleImage entities are found.
func (viq *VehicleImageQuery) Only(ctx context.Context) (*VehicleImage, error) {
	nodes, err := viq.Limit(2).All(setContextOp(ctx, viq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{vehicleimage.Label}
	default:
		return nil, &NotSingularError{vehicleimage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (viq *VehicleImageQuery) OnlyX(ctx context.Context) *VehicleImage {
	node, err := viq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VehicleImage ID in the query.
// Returns a *NotSingularError when more than one VehicleImage ID is found.
// Returns a *NotFoundError when no entities are found.
func (viq *VehicleImageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = viq.Limit(2).IDs(setContextOp(ctx, viq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{vehicleimage.Label}
	default:
		err = &NotSingularError{vehicleimage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (viq *VehicleImageQuery) OnlyIDX(ctx context.Context) int {
	id, err := viq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VehicleImages.
func (viq *VehicleImageQuery) All(ctx context.Context) ([]*VehicleImage, error) {
	ctx = setContextOp(ctx, viq.ctx, "All")
	if err := viq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VehicleImage, *VehicleImageQuery]()
	return withInterceptors[[]*VehicleImage](ctx, viq, qr, viq.inters)
}

// AllX is like All, but panics if an error occurs.
func (viq *VehicleImageQuery) AllX(ctx context.Context) []*VehicleImage {
	nodes, err := viq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VehicleImage IDs.
func (viq *VehicleImageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if viq.ctx.Unique == nil && viq.path != nil {
		viq.Unique(true)
	}
	ctx = setContextOp(ctx, viq.ctx, "IDs")
	if err = viq.Select(vehicleimage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (viq *VehicleImageQuery) IDsX(ctx context.Context) []int {
	ids, err := viq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (viq *VehicleImageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, viq.ctx, "Count")
	if err := viq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, viq, querierCount[*VehicleImageQuery](), viq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (viq *VehicleImageQuery) CountX(ctx context.Context) int {
	count, err := viq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (viq *VehicleImageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, viq.ctx, "Exist")
	switch _, err := viq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (viq *VehicleImageQuery) ExistX(ctx context.Context) bool {
	exist, err := viq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VehicleImageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (viq *VehicleImageQuery) Clone() *VehicleImageQuery {
	if viq == nil {
		return nil
	}
	return &VehicleImageQuery{
		config:      viq.config,
		ctx:         viq.ctx.Clone(),
		order:       append([]vehicleimage.OrderOption{}, viq.order...),
		inters:      append([]Interceptor{}, viq.inters...),
		predicates:  append([]predicate.VehicleImage{}, viq.predicates...),
		withVehicle: viq.withVehicle.Clone(),
		// clone intermediate query.
		sql:  viq.sql.Clone(),
		path: viq.path,
	}
}

// WithVehicle tells the query-builder to eager-load the nodes that are connected to
// the "vehicle" edge. The optional arguments are used to configure the query builder of the edge.
func (viq *VehicleImageQuery) WithVehicle(opts ...func(*VehicleQuery)) *VehicleImageQuery {
	query := (&VehicleClient{config: viq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	viq.withVehicle = query
	return viq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VehicleImage.Query().
//		GroupBy(vehicleimage.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (viq *VehicleImageQuery) GroupBy(field string, fields ...string) *VehicleImageGroupBy {
	viq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VehicleImageGroupBy{build: viq}
	grbuild.flds = &viq.ctx.Fields
	grbuild.label = vehicleimage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.VehicleImage.Query().
//		Select(vehicleimage.FieldCreatedAt).
//		Scan(ctx, &v)
func (viq *VehicleImageQuery) Select(fields ...string) *VehicleImageSelect {
	viq.ctx.Fields = append(viq.ctx.Fields, fields...)
	sbuild := &VehicleImageSelect{VehicleImageQuery: viq}
	sbuild.label = vehicleimage.Label
	sbuild.flds, sbuild.scan = &viq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VehicleImageSelect configured with the given aggregations.
func (viq *VehicleImageQuery) Aggregate(fns ...AggregateFunc) *VehicleImageSelect {
	return viq.Select().Aggregate(fns...)
}

func (viq *VehicleImageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range viq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, viq); err != nil {
				return err
			}
		}
	}
	for _, f := range viq.ctx.Fields {
		if !vehicleimage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if viq.path != nil {
		prev, err := viq.path(ctx)
		if err != nil {
			return err
		}
		viq.sql = prev
	}
	return nil
}

func (viq *VehicleImageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VehicleImage, error) {
	var (
		nodes       = []*VehicleImage{}
		withFKs     = viq.withFKs
		_spec       = viq.querySpec()
		loadedTypes = [1]bool{
			viq.withVehicle != nil,
		}
	)
	if viq.withVehicle != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, vehicleimage.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VehicleImage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VehicleImage{config: viq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(viq.modifiers) > 0 {
		_spec.Modifiers = viq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, viq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := viq.withVehicle; query != nil {
		if err := viq.loadVehicle(ctx, query, nodes, nil,
			func(n *VehicleImage, e *Vehicle) { n.Edges.Vehicle = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (viq *VehicleImageQuery) loadVehicle(ctx context.Context, query *VehicleQuery, nodes []*VehicleImage, init func(*VehicleImage), assign func(*VehicleImage, *Vehicle)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*VehicleImage)
	for i := range nodes {
		if nodes[i].vehicle_images == nil {
			continue
		}
		fk := *nodes[i].vehicle_images
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(vehicle.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "vehicle_images" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (viq *VehicleImageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := viq.querySpec()
	if len(viq.modifiers) > 0 {
		_spec.Modifiers = viq.modifiers
	}
	_spec.Node.Columns = viq.ctx.Fields
	if len(viq.ctx.Fields) > 0 {
		_spec.Unique = viq.ctx.Unique != nil && *viq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, viq.driver, _spec)
}

func (viq *VehicleImageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(vehicleimage.Table, vehicleimage.Columns, sqlgraph.NewFieldSpec(vehicleimage.FieldID, field.TypeInt))
	_spec.From = viq.sql
	if unique := viq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if viq.path != nil {
		_spec.Unique = true
	}
	if fields := viq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vehicleimage.FieldID)
		for i := range fields {
			if fields[i] != vehicleimage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := viq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := viq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := viq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := viq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (viq *VehicleImageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(viq.driver.Dialect())
	t1 := builder.Table(vehicleimage.Table)
	columns := viq.ctx.Fields
	if len(columns) == 0 {
		columns = vehicleimage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if viq.sql != nil {
		selector = viq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if viq.ctx.Unique != nil && *viq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range viq.modifiers {
		m(selector)
	}
	for _, p := range viq.predicates {
		p(selector)
	}
	for _, p := range viq.order {
		p(selector)
	}
	if offset := viq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := viq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (viq *VehicleImageQuery) Modify(modifiers ...func(s *sql.Selector)) *VehicleImageSelect {
	viq.modifiers = append(viq.modifiers, modifiers...)
	return viq.Select()
}

// VehicleImageGroupBy is the group-by builder for VehicleImage entities.
type VehicleImageGroupBy struct {
	selector
	build *VehicleImageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vigb *VehicleImageGroupBy) Aggregate(fns ...AggregateFunc) *VehicleImageGroupBy {
	vigb.fns = append(vigb.fns, fns...)
	return vigb
}

// Scan applies the selector query and scans the result into the given value.
func (vigb *VehicleImageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vigb.build.ctx, "GroupBy")
	if err := vigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VehicleImageQuery, *VehicleImageGroupBy](ctx, vigb.build, vigb, vigb.build.inters, v)
}

func (vigb *VehicleImageGroupBy) sqlScan(ctx context.Context, root *VehicleImageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vigb.fns))
	for _, fn := range vigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vigb.flds)+len(vigb.fns))
		for _, f := range *vigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VehicleImageSelect is the builder for selecting fields of VehicleImage entities.
type VehicleImageSelect struct {
	*VehicleImageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vis *VehicleImageSelect) Aggregate(fns ...AggregateFunc) *VehicleImageSelect {
	vis.fns = append(vis.fns, fns...)
	return vis
}

// Scan applies the selector query and scans the result into the given value.
func (vis *VehicleImageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vis.ctx, "Select")
	if err := vis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VehicleImageQuery, *VehicleImageSelect](ctx, vis.VehicleImageQuery, vis, vis.inters, v)
}

func (vis *VehicleImageSelect) sqlScan(ctx context.Context, root *VehicleImageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vis.fns))
	for _, fn := range vis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (vis *VehicleImageSelect) Modify(modifiers ...func(s *sql.Selector)) *VehicleImageSelect {
	vis.modifiers = append(vis.modifiers, modifiers...)
	return vis
}
