// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BookibusUser is the predicate function for bookibususer builders.
type BookibusUser func(*sql.Selector)

// Booking is the predicate function for booking builders.
type Booking func(*sql.Selector)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// CompanyUser is the predicate function for companyuser builders.
type CompanyUser func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// CustomerContact is the predicate function for customercontact builders.
type CustomerContact func(*sql.Selector)

// CustomerLuggage is the predicate function for customerluggage builders.
type CustomerLuggage func(*sql.Selector)

// Incident is the predicate function for incident builders.
type Incident func(*sql.Selector)

// IncidentImage is the predicate function for incidentimage builders.
type IncidentImage func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// Parcel is the predicate function for parcel builders.
type Parcel func(*sql.Selector)

// ParcelImage is the predicate function for parcelimage builders.
type ParcelImage func(*sql.Selector)

// Passenger is the predicate function for passenger builders.
type Passenger func(*sql.Selector)

// Route is the predicate function for route builders.
type Route func(*sql.Selector)

// RouteStop is the predicate function for routestop builders.
type RouteStop func(*sql.Selector)

// Trip is the predicate function for trip builders.
type Trip func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vehicle is the predicate function for vehicle builders.
type Vehicle func(*sql.Selector)

// VehicleImage is the predicate function for vehicleimage builders.
type VehicleImage func(*sql.Selector)
